zadar/blueprints/about.py
from flask import (
    Blueprint, render_template
)

from zadar.blueprints.auth import login_required

bp = Blueprint('about', __name__, url_prefix='/about')

@bp.route('/')
@login_required
def about():
    return render_template('about/about.html')

zadar/blueprints/auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)

from werkzeug.security import check_password_hash, generate_password_hash

from zadar.db import get_db

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'

        if error is None:
            try:
                db.execute(
                    "INSERT INTO user (username, password) VALUES (?, ?)",
                    (username, generate_password_hash(password)),
                )

                db.commit()
            except db.IntegrityError:
                error = f"User {username} is already registered."
            else:
                return redirect(url_for("auth.login"))

        flash(error)

    return render_template('auth/register.html')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None

        user = db.execute(
            'SELECT * FROM user WHERE username = ?', (username,)
        ).fetchone()

        if user is None:
            error = 'Incorrect username.'
        # hashes the submitted password in the same way as the stored
        # hash and securely compares them. If they match, the password
        # is valid.
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            # session is a dict that stores data across requests.
            # When validation succeeds, the user’s id is stored in
            # a new session. The data is stored in a cookie that is
            # sent to the browser, and the browser then sends it back
            # with subsequent requests. Flask securely signs the data
            # so that it can’t be tampered with.
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('index'))

        flash(error)

    # GET
    return render_template('auth/login.html')

# bp.before_app_request() registers a function that runs before
# the view function, no matter what URL is requested.
# load_logged_in_user checks if a user id is stored in the session
# and gets that user’s data from the database, storing it on g.user,
# which lasts for the length of the request. If there is no user id,
# or if the id doesn’t exist, g.user will be None.


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            # Note the comma after user_id which turns the expression
            # into a tuple with a single element.
            'SELECT * FROM user WHERE id = ?', (user_id, )
        ).fetchone()


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))

# This decorator returns a new view function that wraps the
# original view it’s applied to. The new function checks if a
# user is loaded and redirects to the login page otherwise. If
# a user is loaded the original view is called and continues
# normally.


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

zadar/blueprints/patch.py
import requests, datetime

from flask import (
    Blueprint, render_template
)

from zadar.blueprints.auth import login_required

bp = Blueprint('patch', __name__, url_prefix='/patch')

base_url = 'https://temtem-api.mael.tech/api'
patch_endpoint = 'patches'
limit = 'limit=1'
type_img_endpoint = 'https://temtem-api.mael.tech/images/icons/types/'

@bp.route('/')
@login_required
def patch():
    url = f"{base_url}/{patch_endpoint}?{limit}"
    response = requests.get(url)
    patch = response.json()[0]

    formatted_date = format_date(patch['date'])

    return render_template('patch/patch.html', patch=patch, date=formatted_date)
    
def format_date(date_str):
    date = datetime.datetime.strptime(date_str, '%Y-%m-%d')
    formatted_date = date.strftime('%d %B %Y').replace(' 0', ' ')

    return formatted_date.replace('{S}', 'th').replace('{st}', 'st').replace('{nd}', 'nd').replace('{rd}', 'rd').replace('{th}', 'th')

zadar/blueprints/posts.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from werkzeug.exceptions import abort

from zadar.blueprints.auth import login_required
from zadar.db import get_db

from math import ceil

bp = Blueprint('posts', __name__)


@bp.route('/', methods=('GET', 'POST'))
@login_required
def index():
    category = request.args.get('category', 'ALL', type=str)
    page = request.args.get('page', 1, type=int)

    db = get_db()

    total_posts = 0
    posts_per_page = 5
    current_offset = posts_per_page * (page - 1)

    if category == 'ALL':
        total_posts = db.execute(
            'SELECT COUNT(*) '
            'FROM post'
        ).fetchone()[0]
    else:
        total_posts = db.execute(
            'SELECT COUNT(*) '
            'FROM post '
            'WHERE category = ?',
            (category, )
        ).fetchone()[0]

    if request.method == 'POST':
        category = request.form['category']
        if category == "ALL":
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (posts_per_page, current_offset)
            ).fetchall()
        else:
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.category = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (category, posts_per_page, current_offset)
            ).fetchall()

        if category == 'ALL':
            total_posts = db.execute(
                'SELECT COUNT(*) '
                'FROM post'
            ).fetchone()[0]
        else:
            total_posts = db.execute(
                'SELECT COUNT(*) '
                'FROM post '
                'WHERE category = ?',
                (category, )
            ).fetchone()[0]
        
    else:
        if category == "ALL":
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (posts_per_page, current_offset)
            ).fetchall()
        else:
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.category = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (category, posts_per_page, current_offset)
            ).fetchall()

    total_pages = ceil(total_posts / posts_per_page)

    return render_template(
        'posts/index.html', 
        posts=posts, 
        total_pages=total_pages,
        category=category,
        current_page=page,
        categories=get_categories())

@bp.route('/profile', methods=('GET', 'POST'))
@login_required
def get_profile():
    page = request.args.get('page', 1, type=int)
    category = request.args.get('category', 'ALL', type=str)

    db = get_db()

    total_posts = 0
    posts_per_page  = 5
    current_offset = posts_per_page * (page - 1)

    if category == 'ALL':
        total_posts = db.execute(
            'SELECT COUNT(*) '
            'FROM post p '
            'JOIN user u ON p.author_id = u.id '
            'WHERE p.author_id = ?',
            (g.user['id'],)
        ).fetchone()[0]
    else:
        total_posts = db.execute(
            'SELECT COUNT(*) '
            'FROM post p '
            'JOIN user u ON p.author_id = u.id '
            'WHERE p.author_id = ? AND p.category = ?',
            (g.user['id'], category)
        ).fetchone()[0]

    if request.method == 'POST':
        category = request.form['category']
        if category == "ALL":
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (g.user['id'], posts_per_page , current_offset)
            ).fetchall()
        else:
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ? AND p.category = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (g.user['id'], category, posts_per_page , current_offset)
            ).fetchall()

        if category == 'ALL':
            total_posts = db.execute(
                'SELECT COUNT(*) '
                'FROM post p '
                'JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ?',
                (g.user['id'],)
            ).fetchone()[0]
        else:
            total_posts = db.execute(
                'SELECT COUNT(*) '
                'FROM post p '
                'JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ? AND p.category = ?',
                (g.user['id'], category)
            ).fetchone()[0]
    else:
        if category == "ALL":
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (g.user['id'], posts_per_page , current_offset)
            ).fetchall()
        else:
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ? AND p.category = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (g.user['id'], category, posts_per_page , current_offset)
            ).fetchall()
    
    total_pages = ceil(total_posts / posts_per_page)

    likes = db.execute(
        'SELECT likes.type, COUNT(*) as count '
        'FROM likes '
        'WHERE user_id = ? '
        'GROUP BY likes.type',
        (g.user['id'],)
    ).fetchall()

    likes_count = 0
    dislikes_count = 0

    for row in likes:
        if row['type'] == 'like':
            likes_count = row['count']
        elif row['type'] == 'dislike':
            dislikes_count = row['count']

    prev_page = page - 1 if page > 1 else None
    next_page = page + 1 if page < total_pages else None

    user_timestamp = db.execute(
        'SELECT user_timestamp '
        'FROM user '
        'WHERE id = ? ',
        (g.user['id'],)
    ).fetchone()[0]

    formatted_date = format_date(user_timestamp)

    return render_template(
        'posts/profile.html',
        posts_count=total_posts,
        likes=likes_count,
        dislikes=dislikes_count,
        posts=posts,
        date=formatted_date,
        category=category,
        prev_page=prev_page,
        next_page=next_page,
        page=page,
        total_pages=total_pages,
        categories=get_categories()
    )

@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        category = request.form['category']
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'INSERT INTO post (title, body, category, author_id)'
                ' VALUES (?, ?, ?, ?)',
                (title, body, category, g.user['id'])
            )
            db.commit()
            return redirect(url_for('posts.index'))

    return render_template('posts/create.html', categories=get_categories())


def get_categories():
    return ['GENERAL', 'TEMTEMUP', 'OPINION']

def get_post(id, check_author=True):
    post = get_db().execute(
        'SELECT p.id, title, body, category, created, author_id, username'
        ' FROM post p JOIN user u ON p.author_id = u.id'
        ' WHERE p.id = ?',
        (id,)
    ).fetchone()

    if post is None:
        abort(404, f"Post id {id} doesn't exist.")

    if check_author and post['author_id'] != g.user['id']:
        abort(403)

    return post

def get_comments(id):
    db = get_db()
    comments = db.execute('SELECT c.id, c.post_id, c.user_id, u.username, c.created, c.body '
                          'FROM comments c JOIN user u ON c.user_id = u.id '
                          'WHERE c.post_id = ? '
                          'ORDER BY c.created DESC', (id,)).fetchall()
    
    return comments

@bp.route('/post/<int:id>', methods=['GET', 'POST'])
@login_required
def post(id):
    db = get_db()
    post = get_post(id, False)
    likes = get_likes(id)
    comments = get_comments(id)

    if request.method == 'POST':
        comment_body = request.form['body']
        user_id = g.user['id']
        db.execute('INSERT INTO comments (post_id, user_id, body) VALUES (?, ?, ?)',
                   (id, user_id, comment_body))
        db.commit()

        return redirect(url_for('posts.post', id=id))

    return render_template(
        'posts/post.html', 
        post=post, 
        comments=comments,
        likes=likes, 
        categories=get_categories()
    )

@bp.route('/post/like/<int:id>', methods=['POST'])
@login_required
def like_post(id):
    db = get_db()

    existing_vote = db.execute(
        'SELECT type FROM likes WHERE post_id = ? AND user_id = ?',

zadar/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Zadar - {% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
  </head>
  <body>
    <!-- bootstrap dependencies on top so the individual scripts work -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"
      integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2"
      crossorigin="anonymous"
    ></script>


    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
      <div class="container navbar-container">
        <a class="navbar-brand" href="{{ url_for('posts.index')}}">Zadar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto align-items-center">
            {% if g.user %}
            <li class="nav-item nav-item-img">
              <a class="nav-link" href="{{ url_for('posts.index') }}"
                ><img class="nav-img" src="{{ url_for('static', filename='img/nav/home.png') }}"> Posts</a
              >
            </li>
            <li class="nav-item nav-item-img">
              <a class="nav-link" href="{{ url_for('tempedia.search') }}"
                ><img class="nav-img" src="{{ url_for('static', filename='img/nav/general.png') }}"> Tempedia</a
              >
            </li>
            <li class="nav-item dropdown nav-item-img">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
              <img class="nav-img" src="{{ url_for('static', filename='img/nav/tournaments.png') }}"> Combat
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a
                  class="dropdown-item"
                  href="{{ url_for('type_chart.type_chart') }}"
                  >Type Chart</a
                >
                <a
                class="dropdown-item"
                href="{{ url_for('weaknesses_calculator.calculate') }}"
                >Weaknesses Calculator</a
                >
                <a class="dropdown-item" href="{{ url_for('techniques.search') }}"
                  >Techniques</a
                >
                <a class="dropdown-item" href="{{ url_for('traits.search') }}"
                  >Traits</a
                >
              </div>
            </li>
            <li class="nav-item nav-item-img">
              <a class="nav-link" href="{{ url_for('patch.patch') }}"
                ><img class="nav-img" src="{{ url_for('static', filename='img/nav/bugs.png') }}"> Patch</a
              >
            </li>
            <li class="nav-item nav-item-img">
              <a class="nav-link" href="{{ url_for('about.about') }}"
                ><img class="nav-img" src="{{ url_for('static', filename='img/nav/questions.png') }}"> About</a
              >
            </li>
            <li class="nav-item nav-item-img">
              <a class="nav-link" href="{{ url_for('posts.get_profile' )}}"
                ><img class="nav-img" src="{{ url_for('static', filename='img/nav/media.png') }}"> {{ g.user['username'] }}</a
              >
            </li>
            <li class="nav-item nav-item-img">
              <a class="nav-link" href="{{ url_for('auth.logout') }}">
                <img class="nav-img" src="{{ url_for('static', filename='img/nav/exit.png') }}"> Log Out</a>
            </li>
            {% else %}
            <li class="nav-item nav-item-img">
              <a class="nav-link" href="{{ url_for('auth.register') }}"
                ><img class="nav-img" src="{{ url_for('static', filename='img/nav/feedback.png') }}"> Register</a
              >
            </li>
            <li class="nav-item nav-item-img">
              <a class="nav-link" href="{{ url_for('auth.login') }}">
                <img class="nav-img" src="{{ url_for('static', filename='img/nav/media.png') }}"> Log In</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container my-3">
      <section class="content">
        <header class="text-center">{% block header %}{% endblock %}</header>
        
        {% block content %}{% endblock %}
      </section>
    </div>

    <footer class="text-center my-5">
      <span>Made by
        <a href="https://github.com/JoelEncinas" target="_blank">Joel</a>
        | Powered by <a href="https://temtem-api.mael.tech/" target="_blank">temtem-api</a>
      </span>
    </footer>

    <script src="{{ url_for('static', filename='js/alerts.js') }}"></script>
  </body>
</html>

zadar/templates/flash_msg.html
{% for message in get_flashed_messages() %}
    <div class="alert alert-danger text-center my-3">
        <strong>{{ message }}</strong>
    </div>
{% endfor %}