zadar/blueprints/weaknesses_calculator.py
import requests

from flask import (
    Blueprint, render_template, request
)

from zadar.blueprints.auth import login_required

bp = Blueprint('weaknesses_calculator', __name__, url_prefix='/calculator')

base_url = 'https://temtem-api.mael.tech'
api_endpoint = '/api'
types_endpoint = '/types'
calculate_endpoint = '/weaknesses/calculate/'
type_img_endpoint = f"{base_url}/images/icons/types/"

@bp.route('/', methods=('GET', 'POST'))
@login_required
def calculate():
    types_data = requests.get(f"{base_url}{api_endpoint}{types_endpoint}").json()
    types = {type_data['name'] for type_data in types_data}

    if request.method == 'POST':
        attacking = request.form.get('attacking')
        defending1 = request.form.get('defending1')
        defending2 = request.form.get('defending2')

        if(defending2 == "no-type"):
            response = requests.post(f"{base_url}{api_endpoint}{calculate_endpoint}?attacking={attacking}&defending={defending1}")
            data = response.json()
            return render_template('weaknesses_calculator/result.html', result=data, type_img_endpoint=type_img_endpoint)
        else:
            response = requests.post(f"{base_url}{api_endpoint}{calculate_endpoint}?attacking={attacking}&defending={defending1},{defending2}")
            data = response.json()
            return render_template('weaknesses_calculator/result.html', result=data, type_img_endpoint=type_img_endpoint)

    return render_template('weaknesses_calculator/calculate.html', types=types)

zadar/templates/weaknesses_calculator/calculate.html
{% extends 'base.html' %}

{% block header %}
    <h1 class="display-4">{% block title %}Weaknesses Calculator{% endblock%}</h1>
{% endblock %}

{% block content %}
<div class="container">
    <form class="weakness-calculator-form" method="POST">
        <div class="form-group">
            <label class="form-label mt-4" for="attacking">
                <img class="weakness-calculator-img" src="{{ url_for('static', filename='img/stats/atk.png') }}"> Attacking Type
            </label>
            <select name="attacking" class="form-control" required>
                {% for type_name in types %}
                    <option value="{{ type_name }}">{{ type_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label class="form-label mt-4" for="defending1">
                <img class="weakness-calculator-img" src="{{ url_for('static', filename='img/stats/def.png') }}"> Defending Type 1
            </label>
            <select name="defending1" id="defending1" class="form-control" required>
                {% for type_name in types %}
                    <option value="{{ type_name }}">{{ type_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label class="form-label mt-4" for="defending2">
                <img class="weakness-calculator-img" src="{{ url_for('static', filename='img/stats/def.png') }}"> Defending Type 2
            </label>
            <select name="defending2" id="defending2" class="form-control" required>
                <option value="no-type">No Type</option>
                {% for type_name in types %}
                    <option value="{{ type_name }}">{{ type_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="text-center my-3">
            <button type="submit" class="btn btn-outline-primary">Calculate</button>
        </div>
    </form>
</div>
{% endblock %}

zadar/templates/weaknesses_calculator/result.html
{% extends 'base.html' %}

{% block header %}
    <h1 class="display-4">{% block title %}Effectiveness{% endblock%}</h1>
{% endblock %}

{% block content %}
<div class="container efectiveness-result">
    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">Temtem</th>
                <th scope="col">Type</th>
            </tr>
        </thead>
        <tbody>
            <tr>
              <td scope="row">
                <img class="weakness-calculator-img-small" src="{{ url_for('static', filename='img/stats/atk.png') }}"> Attacking
              </td>
              <td>
                <img class="calculator-type-img" src="{{ type_img_endpoint}}{{ result['attacking'] }}.png" data-toggle="tooltip" data-placement="right" title="{{ result['attacking'] }}" alt="{{ result['attacking'] }}">
              </td>
            </tr>
            {% if result['defending'] | length == 1 %}
            <tr>
              <td scope="row">
                <img class="weakness-calculator-img-small" src="{{ url_for('static', filename='img/stats/def.png') }}"> Defending
              </td>
              <td>
                <img class="calculator-type-img" src="{{ type_img_endpoint}}{{ result['defending'][0] }}.png" data-toggle="tooltip" data-placement="right" title="{{ result['defending'][0] }}" alt="{{ result['defending'][0] }}">
              </td>
            </tr>
            <tr>
              <td scope="row">
                Modifier
              </td>
              <td>
                <span class="fw-bold">x{{ result['modifiers'][0] }}</span>
              </td>
            </tr>
            <tr>
              <td scope="row">
                Result
              </td>
              <td>
                <span class="fw-bold">x{{ result['result'] }}</span>
              </td>
            </tr>
            {% else %}
            <tr>
              <td scope="row">
                <img class="weakness-calculator-img-small" src="{{ url_for('static', filename='img/stats/def.png') }}"> Defending 1
              </td>
              <td>
                <img class="calculator-type-img" src="{{ type_img_endpoint}}{{ result['defending'][0] }}.png" data-toggle="tooltip" data-placement="right" title="{{ result['defending'][0] }}" alt="{{ result['defending'][0] }}">
              </td>
            </tr>
            <tr>
            <tr>
              <td scope="row">
                <img class="weakness-calculator-img-small" src="{{ url_for('static', filename='img/stats/def.png') }}"> Defending 2
              </td>
              <td>
                <img class="calculator-type-img" src="{{ type_img_endpoint}}{{ result['defending'][1] }}.png" data-toggle="tooltip" data-placement="right" title="{{ result['defending'][1] }}" alt="{{ result['defending'][1] }}">
              </td>
            </tr>
            <tr>    
              <td scope="row">
                  Modifier 1
              </td>
              <td>
                <span class="fw-bold">x{{ result['modifiers'][0] }}</span>
              </td>
            </tr>
            <tr>
              <td scope="row">
                Modifier 2
              </td>
              <td>
                <span class="fw-bold">x{{ result['modifiers'][1] }}</span>
              </td>
            </tr>
            <tr>
              <td scope="row">
                Result
              </td>
              <td>
                <span class="fw-bold">x{{ result['result'] }}</span>
              </td>
            </tr>
            {% endif %}
        </tbody>
    </table>

    <div class="text-center my-4">
        <a href="{{ url_for('weaknesses_calculator.calculate') }}" class="btn btn-outline-primary">Back to calculator</a>
    </div>
</div>

<script src="{{ url_for('static', filename='js/activateTooltip.js') }}"></script>
{% endblock %}