zadar/blueprints/posts.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from werkzeug.exceptions import abort

from zadar.blueprints.auth import login_required
from zadar.db import get_db

from math import ceil

bp = Blueprint('posts', __name__)


@bp.route('/', methods=('GET', 'POST'))
@login_required
def index():
    category = request.args.get('category', 'ALL', type=str)
    page = request.args.get('page', 1, type=int)

    db = get_db()

    total_posts = 0
    posts_per_page = 5
    current_offset = posts_per_page * (page - 1)

    if category == 'ALL':
        total_posts = db.execute(
            'SELECT COUNT(*) '
            'FROM post'
        ).fetchone()[0]
    else:
        total_posts = db.execute(
            'SELECT COUNT(*) '
            'FROM post '
            'WHERE category = ?',
            (category, )
        ).fetchone()[0]

    if request.method == 'POST':
        category = request.form['category']
        if category == "ALL":
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (posts_per_page, current_offset)
            ).fetchall()
        else:
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.category = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (category, posts_per_page, current_offset)
            ).fetchall()

        if category == 'ALL':
            total_posts = db.execute(
                'SELECT COUNT(*) '
                'FROM post'
            ).fetchone()[0]
        else:
            total_posts = db.execute(
                'SELECT COUNT(*) '
                'FROM post '
                'WHERE category = ?',
                (category, )
            ).fetchone()[0]
        
    else:
        if category == "ALL":
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (posts_per_page, current_offset)
            ).fetchall()
        else:
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.category = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (category, posts_per_page, current_offset)
            ).fetchall()

    total_pages = ceil(total_posts / posts_per_page)

    return render_template(
        'posts/index.html', 
        posts=posts, 
        total_pages=total_pages,
        category=category,
        current_page=page,
        categories=get_categories())

@bp.route('/profile', methods=('GET', 'POST'))
@login_required
def get_profile():
    page = request.args.get('page', 1, type=int)
    category = request.args.get('category', 'ALL', type=str)

    db = get_db()

    total_posts = 0
    posts_per_page  = 5
    current_offset = posts_per_page * (page - 1)

    if category == 'ALL':
        total_posts = db.execute(
            'SELECT COUNT(*) '
            'FROM post p '
            'JOIN user u ON p.author_id = u.id '
            'WHERE p.author_id = ?',
            (g.user['id'],)
        ).fetchone()[0]
    else:
        total_posts = db.execute(
            'SELECT COUNT(*) '
            'FROM post p '
            'JOIN user u ON p.author_id = u.id '
            'WHERE p.author_id = ? AND p.category = ?',
            (g.user['id'], category)
        ).fetchone()[0]

    if request.method == 'POST':
        category = request.form['category']
        if category == "ALL":
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (g.user['id'], posts_per_page , current_offset)
            ).fetchall()
        else:
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ? AND p.category = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (g.user['id'], category, posts_per_page , current_offset)
            ).fetchall()

        if category == 'ALL':
            total_posts = db.execute(
                'SELECT COUNT(*) '
                'FROM post p '
                'JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ?',
                (g.user['id'],)
            ).fetchone()[0]
        else:
            total_posts = db.execute(
                'SELECT COUNT(*) '
                'FROM post p '
                'JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ? AND p.category = ?',
                (g.user['id'], category)
            ).fetchone()[0]
    else:
        if category == "ALL":
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (g.user['id'], posts_per_page , current_offset)
            ).fetchall()
        else:
            posts = db.execute(
                'SELECT p.id, title, body, category, created, author_id, username '
                'FROM post p JOIN user u ON p.author_id = u.id '
                'WHERE p.author_id = ? AND p.category = ? '
                'ORDER BY created DESC '
                'LIMIT ? OFFSET ?',
                (g.user['id'], category, posts_per_page , current_offset)
            ).fetchall()
    
    total_pages = ceil(total_posts / posts_per_page)

    likes = db.execute(
        'SELECT likes.type, COUNT(*) as count '
        'FROM likes '
        'WHERE user_id = ? '
        'GROUP BY likes.type',
        (g.user['id'],)
    ).fetchall()

    likes_count = 0
    dislikes_count = 0

    for row in likes:
        if row['type'] == 'like':
            likes_count = row['count']
        elif row['type'] == 'dislike':
            dislikes_count = row['count']

    prev_page = page - 1 if page > 1 else None
    next_page = page + 1 if page < total_pages else None

    user_timestamp = db.execute(
        'SELECT user_timestamp '
        'FROM user '
        'WHERE id = ? ',
        (g.user['id'],)
    ).fetchone()[0]

    formatted_date = format_date(user_timestamp)

    return render_template(
        'posts/profile.html',
        posts_count=total_posts,
        likes=likes_count,
        dislikes=dislikes_count,
        posts=posts,
        date=formatted_date,
        category=category,
        prev_page=prev_page,
        next_page=next_page,
        page=page,
        total_pages=total_pages,
        categories=get_categories()
    )

@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        category = request.form['category']
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'INSERT INTO post (title, body, category, author_id)'
                ' VALUES (?, ?, ?, ?)',
                (title, body, category, g.user['id'])
            )
            db.commit()
            return redirect(url_for('posts.index'))

    return render_template('posts/create.html', categories=get_categories())


def get_categories():
    return ['GENERAL', 'TEMTEMUP', 'OPINION']

def get_post(id, check_author=True):
    post = get_db().execute(
        'SELECT p.id, title, body, category, created, author_id, username'
        ' FROM post p JOIN user u ON p.author_id = u.id'
        ' WHERE p.id = ?',
        (id,)
    ).fetchone()

    if post is None:
        abort(404, f"Post id {id} doesn't exist.")

    if check_author and post['author_id'] != g.user['id']:
        abort(403)

    return post

def get_comments(id):
    db = get_db()
    comments = db.execute('SELECT c.id, c.post_id, c.user_id, u.username, c.created, c.body '
                          'FROM comments c JOIN user u ON c.user_id = u.id '
                          'WHERE c.post_id = ? '
                          'ORDER BY c.created DESC', (id,)).fetchall()
    
    return comments

@bp.route('/post/<int:id>', methods=['GET', 'POST'])
@login_required
def post(id):
    db = get_db()
    post = get_post(id, False)
    likes = get_likes(id)
    comments = get_comments(id)

    if request.method == 'POST':
        comment_body = request.form['body']
        user_id = g.user['id']
        db.execute('INSERT INTO comments (post_id, user_id, body) VALUES (?, ?, ?)',
                   (id, user_id, comment_body))
        db.commit()

        return redirect(url_for('posts.post', id=id))

    return render_template(
        'posts/post.html', 
        post=post, 
        comments=comments,
        likes=likes, 
        categories=get_categories()
    )

@bp.route('/post/like/<int:id>', methods=['POST'])
@login_required
def like_post(id):
    db = get_db()

    existing_vote = db.execute(
        'SELECT type FROM likes WHERE post_id = ? AND user_id = ?',

zadar/templates/posts/create.html
{% extends 'base.html' %}

{% block header %}
  <h1 class="display-4">{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="container">
  <div class="post-container">
    <form method="POST">
      <div class="form-group">
        <label class="form-label mt-4" for="title">Title</label>
        <input class="form-control" name="title" id="title"
        value="{{ request.form['title'] }}" maxlength="30" required>
      </div>
      <div class="form-group">
        <label class="form-label mt-4" for="category">Category</label>
        <select class="form-control" name="category" id="category">
          {% for category in categories %}
            {% if request.form['category'] == category %}
              <option selected>{{ category }}</option>
            {% else %}
              <option>{{ category }}</option>
            {% endif %}
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label class="form-label mt-4" for="body">Body</label>
        <textarea class="form-control" name="body" id="body" maxlength="100">{{ request.form['body'] }}</textarea>
        <div id="character-counter">0/100</div>
      </div>
      <div class="text-center py-3">
        <input class="btn btn-outline-primary" type="submit" value="Save">
      </div>

      {% include 'flash_msg.html' %}
    </form>
  </div>
</div>

<script src="{{ url_for('static', filename='js/characterCounter.js') }}"></script>
{% endblock %}

zadar/templates/posts/create_post_button.html
{% if g.user %}
<div class="text-center my-3">
  <a class="btn btn-primary" href="{{ url_for('posts.create') }}">New Post</a>
</div>
{% endif %}

zadar/templates/posts/index.html
{% extends 'base.html' %}

{% block header %}
  <h1 class="display-4">{% block title %}Posts{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="container">
{% include 'posts/create_post_button.html' %}
</div>

<div class="container">
  <div class="filter-container text-center">
    <form method="post" action="{{ url_for('posts.index') }}">
      {% include 'posts/posts_filter.html' %}
    </form>
  </div>
</div>

{% include 'posts/posts_container.html' %}

<div class="container d-flex justify-content-center pt-5">
  <ul class="pagination">
    {% if current_page > 1 %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('index', page=current_page-1, category=category) }}">Prev</a>
      </li>
    {% endif %}
    {% for page_num in range(1, total_pages + 1) %}
      {% if page_num == current_page %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ page_num }}</a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="{{ url_for('index', page=page_num, category=category) }}">{{ page_num }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if current_page < total_pages %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('index', page=current_page+1, category=category) }}">Next</a>
      </li>
    {% endif %}
  </ul>
</div>
{% endblock %}

zadar/templates/posts/post.html
{% extends 'base.html' %}

{% block header %}
  <h1 class="display-4">{% block title %}Post Info{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="container">
  <div class="post-container">
    <div class="card post">
      <div class="card-body post-body">
        <h2 class="card-title py-1">{{ post['title'] }}</h2>
        <h6 class="card-subtitle py-1">
          <span class="fw-normal">By</span> {{ post['username'] }} &nbsp;
          <small class="fst-italic fw-light text-muted">{{ post['created'].strftime('%Y-%m-%d') }}</small> &nbsp;
          {% if post['category'] == categories[0] %}
          <span class="badge bg-primary">General</span>
          {% endif %}
          {% if post['category'] == categories[1] %}
            <span class="badge bg-secondary">Temtemup</span>
          {% endif %}
          {% if post['category'] == categories[2] %}
            <span class="badge bg-info">Opinion</span>
          {% endif %}
        </h6>
        <p class="card-text mt-3 post-text">{{ post['body'] }}</p>
        {% if g.user['id'] == post['author_id'] %}
          <a class="action" href="{{ url_for('posts.update', id=post['id']) }}">Edit</a>
        {% endif %}

        <div class="my-2">
          <form class="d-inline" action="{{ url_for('posts.like_post', id=post['id']) }}" method="POST">
            <input name="like" id="like" value="like" hidden>
            <span class="like-text">{{ likes.likes }}</span>
            &nbsp;
            <input class="btn btn-sm btn-outline-info" type="submit" value="Like">
          </form>
          &nbsp;
          <form class="d-inline" action="{{ url_for('posts.like_post', id=post['id']) }}" method="POST">
            <input name="dislike" id="dislike" value="dislike" hidden>
            <span class="like-text">{{ likes.dislikes }}</span>
            &nbsp;
            <input class="btn btn-sm btn-outline-danger" type="submit" value="Dislike">
          </form>
        </div>
      </div>
    </div>

    {% for message in get_flashed_messages() %}
      <div class="alert alert-danger text-center my-3">
        <strong>{{ message }}</strong>
      </div>
    {% endfor %}

    <div class="comments">
      {% if g.user %}
        <h2 class="pb-0">Add a comment</h2>
        <form action="{{ url_for('posts.post', id=post['id']) }}" method="POST">
          <div class="form-group">
            <label class="form-label mt-2" for="body">Comment:</label>
            <textarea class="form-control" id="body" name="body" maxlength="100" required></textarea>
            <div id="character-counter">0/100</div>
          </div>
          <div class="text-center my-3 pb-5">
            <input class="btn btn-primary" type="submit" value="Add Comment">
          </div>
        </form>
      {% endif %}

      <h2>Comments</h2>
      {% if comments%}
        {% for comment in comments %}
          <div class="comment">
            <span class="fw-normal">By</span> <span class="fw-bold">{{ comment['username'] }}</span> &nbsp;
            <small class="fst-italic fw-light text-muted">{{ comment['created'].strftime('%Y-%m-%d') }}</small> &nbsp;
            <p class="pt-1">{{ comment['body'] }}</p>
          </div>
          <hr>
        {% endfor %}
      {% else %}
          <p>No comments yet!</p>
      {% endif %}
    </div>

  </div>
</div>

<script src="{{ url_for('static', filename='js/characterCounter.js') }}"></script>
{% endblock %}

zadar/templates/posts/posts_container.html
<div class="container">
    <div class="posts-container">
      {% for post in posts %}
        <div class="card post">
          <div class="card-body post-body">
            <h2 class="card-title py-1"><a href="{{ url_for('posts.post', id=post['id']) }}">{{ post['title'] }}</a></h2>
            <h6 class="card-subtitle py-1">
              <span class="fw-normal">By</span> {{ post['username'] }} &nbsp;
              <small class="text-muted fst-italic">{{ post['created'].strftime('%Y-%m-%d') }}</small> &nbsp;
              {% if post['category'] == categories[0] %}
              <span class="badge bg-primary">General</span>
              {% endif %}
              {% if post['category'] == categories[1] %}
                <span class="badge bg-secondary">Temtemup</span>
              {% endif %}
              {% if post['category'] == categories[2] %}
                <span class="badge bg-info">Opinion</span>
              {% endif %}
            </h6>
            <p class="card-text mt-3 post-text">{{ post['body'] }}</p>
            {% if g.user['id'] == post['author_id'] %}
              <a class="action" href="{{ url_for('posts.update', id=post['id']) }}">Edit</a>
            {% endif %}
          </div>
        </a>
      </div>
    </div>
    {% endfor %}
</div>

zadar/templates/posts/posts_filter.html
<div class="form-group text-center">
    <label class="form-label h5" for="category">Category</label>
    <select class="form-control form-control-sm w-50 text-center mx-auto" name="category" id="category">
        <option value="ALL">ALL</option>
        {% for category in categories %}
        {% if request.form['category'] == category %}
            <option selected>{{ category }}</option>
        {% else %}
            <option>{{ category }}</option>
        {% endif %}
        {% endfor %}
    </select>
</div>
<div class="text-center py-3">
    <button type="submit" class="btn btn-sm btn-outline-primary">Filter</button>
</div>

zadar/templates/posts/profile.html
{% extends 'base.html' %}

{% block header %}
  <h1 class="display-4 pb-0">{% block title %}{{ g.user['username'] }}{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="container">
  <div class="profile-container text-center">
    <div class="mb-2">
      <span class="badge bg-success has-tooltip" data-toggle="tooltip" data-placement="top" title="Created an account">Welcome!</span>
      {% if likes + dislikes >= 10 %}
        <span class="badge bg-light has-tooltip" data-toggle="tooltip" data-placement="top" title="Casted 10 or more votes">Active voter</span>
      {% endif %}
      {% if posts_count >= 1 %}
        <span class="badge bg-light has-tooltip" data-toggle="tooltip" data-placement="top" title="Created 1 or more posts">Newbie</span>
      {% endif %}
      {% if posts_count >= 10 %}
        <span class="badge bg-dark has-tooltip" data-toggle="tooltip" data-placement="top" title="Created 10 or more posts">Veteran</span>
      {% endif %}
    </div>

    <div class="mb-3">
      <small><span class="fw-bold">Created on</span> <span class="fst-italic">{{ date }}</span></small>
    </div>

    <div>
      <table class="table text-center">
        <tbody>
        <tr>
            <th scope="row">Posts</th>
            <td>{{ posts_count }}</td>
        </tr>
        <tr>
          <th scope="row">Likes / Dislikes</th>
          <td><span class="text-primary fw-bold">{{ likes }}</span> / <span class="text-danger fw-bold">{{ dislikes }}</span></td>
        </tr>
        <tr>
          <th scope="row">Total Votes</th>
          <td>{{ likes + dislikes }}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>

  {% include 'posts/create_post_button.html' %}
</div>

<div class="container">
  <h2 class="text-center pb-0 pt-5">My Posts</h2>
  <div class="filter-container text-center">
    <form method="post" action="{{ url_for('posts.get_profile') }}">
      {% include 'posts/posts_filter.html' %}
    </form>
  </div>
</div>

{% include 'posts/posts_container.html' %}

<div class="container d-flex justify-content-center pt-5">
  <ul class="pagination">
    {% if prev_page is not none %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('posts.get_profile', page=prev_page, category=category) }}">Previous</a>
      </li>
    {% endif %}

    {% for page_num in range(1, total_pages + 1) %}
      {% if page_num == page %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ page_num }}</a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="{{ url_for('posts.get_profile', page=page_num, category=category) }}">{{ page_num }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if next_page is not none %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('posts.get_profile', page=next_page, category=category) }}">Next</a>
      </li>
    {% endif %}
  </ul>
</div>

<script src="{{ url_for('static', filename='js/activateTooltip.js') }}"></script>
{% endblock %}

zadar/templates/posts/update.html
{% extends 'base.html' %}

{% block header %}
  <h1 class="display-4"><small class="text-muted fw-normal">Edit</small> - {% block title %}{{ post['title'] }}{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="container">
  <div class="post-container">
    <form method="POST">
      <div class="form-group">
        <label class="form-label mt-4" for="title">Title</label>
        <input class="form-control" name="title" id="title"
        value="{{ request.form['title'] or post['title'] }}" maxlength="30" required>
      </div>
      <div class="form-group">
        <label class="form-label mt-4" for="category">Category</label>
        <select class="form-control" name="category" id="category">
          {% for category in categories %}
            {% if request.form['category'] == category %}
              <option selected>{{ category }}</option>
            {% else %}
              <option>{{ category }}</option>
            {% endif %}
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label class="form-label mt-4" for="body">Body</label>
        <textarea class="form-control" name="body" id="body" maxlength="100">{{ request.form['body'] or post['body'] }}</textarea>
        <div id="character-counter">0/100</div>
      </div>
      <div class="text-center py-3">
        <input class="btn btn-outline-primary" type="submit" value="Save">
      </div>

      {% include 'flash_msg.html' %}
    </form>

    <div class="text-center py-3">
      <form class="d-inline" action="{{ url_for('posts.delete', id=post['id']) }}" method="POST">
          <input class="btn btn-outline-danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
      </form>
    </div>
  </div>
</div>

<script src="{{ url_for('static', filename='js/characterCounter.js') }}"></script>
{% endblock %}